/*
Unified
==============
*/
import * as Joi from 'joi';

export const joiApiCallType = Joi.string().valid(
	'login',
	'webhook',
	'inbound',
	'mcp');

export const joiIntegrationAuthType = Joi.string().valid(
	'oauth1',
	'oauth2',
	'other',
	'token');

export const joiIntegrationCategory = Joi.string().valid(
	'passthrough',
	'hris',
	'ats',
	'auth',
	'crm',
	'enrich',
	'martech',
	'ticketing',
	'uc',
	'accounting',
	'storage',
	'commerce',
	'payment',
	'genai',
	'messaging',
	'kms',
	'task',
	'scim',
	'lms',
	'repo',
	'metadata',
	'calendar',
	'verification',
	'ads');

export const joiIntegrationPermission = Joi.string().valid(
	'accounting_account_read',
	'accounting_account_write',
	'accounting_transaction_read',
	'accounting_transaction_write',
	'accounting_journal_read',
	'accounting_journal_write',
	'accounting_invoice_read',
	'accounting_invoice_write',
	'accounting_bill_read',
	'accounting_bill_write',
	'accounting_creditmemo_read',
	'accounting_creditmemo_write',
	'accounting_contact_read',
	'accounting_contact_write',
	'accounting_expense_read',
	'accounting_expense_write',
	'accounting_taxrate_read',
	'accounting_taxrate_write',
	'accounting_organization_read',
	'accounting_order_read',
	'accounting_order_write',
	'accounting_purchaseorder_read',
	'accounting_purchaseorder_write',
	'accounting_salesorder_read',
	'accounting_salesorder_write',
	'accounting_report_read',
	'accounting_report_write',
	'accounting_trialbalance_read',
	'accounting_trialbalance_write',
	'accounting_profitloss_read',
	'accounting_profitloss_write',
	'accounting_balancesheet_read',
	'accounting_balancesheet_write',
	'accounting_category_read',
	'accounting_category_write',
	'payment_payment_read',
	'payment_payment_write',
	'accounting_cashflow_read',
	'accounting_cashflow_write',
	'payment_payout_read',
	'payment_refund_read',
	'payment_link_read',
	'payment_link_write',
	'payment_subscription_read',
	'payment_subscription_write',
	'commerce_item_read',
	'commerce_item_write',
	'commerce_collection_read',
	'commerce_collection_write',
	'commerce_inventory_read',
	'commerce_inventory_write',
	'commerce_location_read',
	'commerce_location_write',
	'commerce_review_read',
	'commerce_review_write',
	'commerce_saleschannel_read',
	'commerce_saleschannel_write',
	'verification_package_read',
	'verification_request_read',
	'verification_request_write',
	'ats_activity_read',
	'ats_activity_write',
	'ats_application_read',
	'ats_application_write',
	'ats_applicationstatus_read',
	'ats_candidate_read',
	'ats_candidate_write',
	'ats_interview_read',
	'ats_interview_write',
	'ats_job_read',
	'ats_job_write',
	'ats_company_read',
	'ats_company_write',
	'ats_document_read',
	'ats_document_write',
	'ats_scorecard_read',
	'ats_scorecard_write',
	'crm_company_read',
	'crm_company_write',
	'crm_contact_read',
	'crm_contact_write',
	'crm_deal_read',
	'crm_deal_write',
	'crm_event_read',
	'crm_event_write',
	'crm_lead_read',
	'crm_lead_write',
	'crm_pipeline_read',
	'crm_pipeline_write',
	'martech_list_read',
	'martech_list_write',
	'martech_member_read',
	'martech_member_write',
	'ticketing_customer_read',
	'ticketing_customer_write',
	'ticketing_ticket_read',
	'ticketing_ticket_write',
	'ticketing_note_read',
	'ticketing_note_write',
	'ticketing_category_read',
	'ticketing_category_write',
	'hris_employee_read',
	'hris_employee_write',
	'hris_group_read',
	'hris_group_write',
	'hris_payslip_read',
	'hris_payslip_write',
	'hris_timeoff_read',
	'hris_timeoff_write',
	'hris_timeshift_read',
	'hris_timeshift_write',
	'hris_company_read',
	'hris_company_write',
	'hris_location_read',
	'hris_location_write',
	'hris_device_read',
	'hris_device_write',
	'hris_deduction_read',
	'hris_deduction_write',
	'hris_benefit_read',
	'hris_benefit_write',
	'uc_call_read',
	'uc_contact_read',
	'uc_contact_write',
	'uc_comment_read',
	'uc_comment_write',
	'uc_recording_read',
	'storage_file_read',
	'storage_file_write',
	'webhook',
	'genai_model_read',
	'genai_prompt_read',
	'genai_prompt_write',
	'genai_embedding_read',
	'genai_embedding_write',
	'messaging_message_read',
	'messaging_message_write',
	'messaging_channel_read',
	'messaging_event_read',
	'messaging_event_write',
	'kms_space_read',
	'kms_space_write',
	'kms_page_read',
	'kms_page_write',
	'kms_comment_read',
	'kms_comment_write',
	'task_project_read',
	'task_project_write',
	'task_task_read',
	'task_task_write',
	'task_change_read',
	'task_comment_read',
	'task_comment_write',
	'scim_users_read',
	'scim_users_write',
	'scim_groups_read',
	'scim_groups_write',
	'lms_course_read',
	'lms_course_write',
	'lms_class_read',
	'lms_class_write',
	'lms_student_read',
	'lms_student_write',
	'lms_instructor_read',
	'lms_instructor_write',
	'repo_organization_read',
	'repo_organization_write',
	'repo_repository_read',
	'repo_repository_write',
	'repo_branch_read',
	'repo_branch_write',
	'repo_commit_read',
	'repo_commit_write',
	'repo_pullrequest_read',
	'repo_pullrequest_write',
	'metadata_metadata_read',
	'metadata_metadata_write',
	'calendar_calendar_read',
	'calendar_calendar_write',
	'calendar_event_read',
	'calendar_event_write',
	'calendar_busy_read',
	'calendar_link_read',
	'calendar_link_write',
	'calendar_recording_read',
	'calendar_recording_write',
	'enrich_person_read',
	'enrich_company_read',
	'ads_ad_read',
	'ads_ad_write',
	'ads_campaign_read',
	'ads_campaign_write',
	'ads_group_read',
	'ads_group_write',
	'ads_report_read',
	'ads_organization_read',
	'ads_organization_write');

export const joiIntegrationSupportWebhookType = Joi.string().valid(
	'virtual',
	'native');

export const joiIssueStatus = Joi.string().valid(
	'COMPLETED',
	'NEW',
	'ROADMAP',
	'IN_PROGRESS',
	'ON_HOLD',
	'VALIDATING',
	'REJECTED');

export const joiObjectType = Joi.string().valid(
	'accounting_account',
	'accounting_transaction',
	'accounting_journal',
	'accounting_contact',
	'accounting_invoice',
	'accounting_bill',
	'accounting_creditmemo',
	'accounting_taxrate',
	'accounting_organization',
	'accounting_order',
	'accounting_salesorder',
	'accounting_purchaseorder',
	'accounting_report',
	'accounting_balancesheet',
	'accounting_profitloss',
	'accounting_trialbalance',
	'accounting_category',
	'accounting_expense',
	'accounting_cashflow',
	'payment_payment',
	'payment_link',
	'payment_payout',
	'payment_refund',
	'payment_subscription',
	'commerce_item',
	'commerce_collection',
	'commerce_inventory',
	'commerce_location',
	'commerce_review',
	'commerce_saleschannel',
	'verification_package',
	'verification_request',
	'ats_activity',
	'ats_application',
	'ats_applicationstatus',
	'ats_candidate',
	'ats_document',
	'ats_interview',
	'ats_job',
	'ats_scorecard',
	'ats_company',
	'crm_company',
	'crm_contact',
	'crm_deal',
	'crm_event',
	'crm_lead',
	'crm_pipeline',
	'hris_employee',
	'hris_group',
	'hris_payslip',
	'hris_timeoff',
	'hris_company',
	'hris_location',
	'hris_device',
	'hris_timeshift',
	'hris_deduction',
	'hris_benefit',
	'martech_list',
	'martech_member',
	'passthrough',
	'ticketing_note',
	'ticketing_ticket',
	'ticketing_customer',
	'ticketing_category',
	'uc_contact',
	'uc_call',
	'uc_comment',
	'uc_recording',
	'enrich_person',
	'enrich_company',
	'storage_file',
	'genai_model',
	'genai_prompt',
	'genai_embedding',
	'messaging_message',
	'messaging_channel',
	'messaging_event',
	'kms_space',
	'kms_page',
	'kms_comment',
	'task_project',
	'task_task',
	'task_comment',
	'task_change',
	'scim_users',
	'scim_groups',
	'lms_course',
	'lms_class',
	'lms_student',
	'lms_instructor',
	'repo_organization',
	'repo_repository',
	'repo_branch',
	'repo_commit',
	'repo_pullrequest',
	'metadata_metadata',
	'calendar_calendar',
	'calendar_event',
	'calendar_busy',
	'calendar_link',
	'calendar_recording',
	'ads_organization',
	'ads_ad',
	'ads_campaign',
	'ads_report',
	'ads_group');

export const joiPlanTerm = Joi.string().valid(
	'monthly',
	'yearly');

export const joiSupportInboundType = Joi.string().valid(
	'supported-required',
	'supported',
	'not-supported');

export const joiSupportOutboundType = Joi.string().valid(
	'supported',
	'not-supported');

export const joiWebhookDatabaseType = Joi.string().valid(
	'mongodb',
	'mysql',
	'postgres',
	'mssql',
	'mariadb',
	'supabase');

export const joiWebhookDataType = Joi.string().valid(
	'INITIAL-PARTIAL',
	'INITIAL-COMPLETE',
	'VIRTUAL',
	'NATIVE');

export const joiWebhookEvent = Joi.string().valid(
	'updated',
	'created',
	'deleted');

export const joiWorkspaceEventType = Joi.string().valid(
	'USER_CREATED',
	'USER_DELETED',
	'CONNECTION_HEALTHY',
	'CONNECTION_UNHEALTHY',
	'CONNECTION_CREATED',
	'CONNECTION_UPDATED',
	'CONNECTION_DELETED',
	'CONNECTION_PAUSED',
	'CONNECTION_UNPAUSED',
	'INTEGRATION_ACTIVATED',
	'INTEGRATION_DEACTIVATED',
	'INTEGRATION_UPDATED',
	'WORKSPACE_UPDATED',
	'WORKSPACE_OVER_LIMIT',
	'WORKSPACE_80PERCENT_LIMIT',
	'WEBHOOK_CREATED',
	'WEBHOOK_DELETED',
	'WEBHOOK_UNHEALTHY',
	'WEBHOOK_PAUSED',
	'WEBHOOK_UNPAUSED');

export const joimap_WebhookEvent_IntegrationSupportWebhookType = Joi.object({
	updated: Joi.array().items(joiIntegrationSupportWebhookType).optional(),
	created: Joi.array().items(joiIntegrationSupportWebhookType).optional(),
	deleted: Joi.array().items(joiIntegrationSupportWebhookType).optional(),
}).label('map_WebhookEvent_IntegrationSupportWebhookType');

export const joimap_IntegrationPermission_string = Joi.object({
	accounting_account_read: Joi.string().allow(null, '').optional(),
	accounting_account_write: Joi.string().allow(null, '').optional(),
	accounting_transaction_read: Joi.string().allow(null, '').optional(),
	accounting_transaction_write: Joi.string().allow(null, '').optional(),
	accounting_journal_read: Joi.string().allow(null, '').optional(),
	accounting_journal_write: Joi.string().allow(null, '').optional(),
	accounting_invoice_read: Joi.string().allow(null, '').optional(),
	accounting_invoice_write: Joi.string().allow(null, '').optional(),
	accounting_bill_read: Joi.string().allow(null, '').optional(),
	accounting_bill_write: Joi.string().allow(null, '').optional(),
	accounting_creditmemo_read: Joi.string().allow(null, '').optional(),
	accounting_creditmemo_write: Joi.string().allow(null, '').optional(),
	accounting_contact_read: Joi.string().allow(null, '').optional(),
	accounting_contact_write: Joi.string().allow(null, '').optional(),
	accounting_expense_read: Joi.string().allow(null, '').optional(),
	accounting_expense_write: Joi.string().allow(null, '').optional(),
	accounting_taxrate_read: Joi.string().allow(null, '').optional(),
	accounting_taxrate_write: Joi.string().allow(null, '').optional(),
	accounting_organization_read: Joi.string().allow(null, '').optional(),
	accounting_order_read: Joi.string().allow(null, '').optional(),
	accounting_order_write: Joi.string().allow(null, '').optional(),
	accounting_purchaseorder_read: Joi.string().allow(null, '').optional(),
	accounting_purchaseorder_write: Joi.string().allow(null, '').optional(),
	accounting_salesorder_read: Joi.string().allow(null, '').optional(),
	accounting_salesorder_write: Joi.string().allow(null, '').optional(),
	accounting_report_read: Joi.string().allow(null, '').optional(),
	accounting_report_write: Joi.string().allow(null, '').optional(),
	accounting_trialbalance_read: Joi.string().allow(null, '').optional(),
	accounting_trialbalance_write: Joi.string().allow(null, '').optional(),
	accounting_profitloss_read: Joi.string().allow(null, '').optional(),
	accounting_profitloss_write: Joi.string().allow(null, '').optional(),
	accounting_balancesheet_read: Joi.string().allow(null, '').optional(),
	accounting_balancesheet_write: Joi.string().allow(null, '').optional(),
	accounting_category_read: Joi.string().allow(null, '').optional(),
	accounting_category_write: Joi.string().allow(null, '').optional(),
	payment_payment_read: Joi.string().allow(null, '').optional(),
	payment_payment_write: Joi.string().allow(null, '').optional(),
	accounting_cashflow_read: Joi.string().allow(null, '').optional(),
	accounting_cashflow_write: Joi.string().allow(null, '').optional(),
	payment_payout_read: Joi.string().allow(null, '').optional(),
	payment_refund_read: Joi.string().allow(null, '').optional(),
	payment_link_read: Joi.string().allow(null, '').optional(),
	payment_link_write: Joi.string().allow(null, '').optional(),
	payment_subscription_read: Joi.string().allow(null, '').optional(),
	payment_subscription_write: Joi.string().allow(null, '').optional(),
	commerce_item_read: Joi.string().allow(null, '').optional(),
	commerce_item_write: Joi.string().allow(null, '').optional(),
	commerce_collection_read: Joi.string().allow(null, '').optional(),
	commerce_collection_write: Joi.string().allow(null, '').optional(),
	commerce_inventory_read: Joi.string().allow(null, '').optional(),
	commerce_inventory_write: Joi.string().allow(null, '').optional(),
	commerce_location_read: Joi.string().allow(null, '').optional(),
	commerce_location_write: Joi.string().allow(null, '').optional(),
	commerce_review_read: Joi.string().allow(null, '').optional(),
	commerce_review_write: Joi.string().allow(null, '').optional(),
	commerce_saleschannel_read: Joi.string().allow(null, '').optional(),
	commerce_saleschannel_write: Joi.string().allow(null, '').optional(),
	verification_package_read: Joi.string().allow(null, '').optional(),
	verification_request_read: Joi.string().allow(null, '').optional(),
	verification_request_write: Joi.string().allow(null, '').optional(),
	ats_activity_read: Joi.string().allow(null, '').optional(),
	ats_activity_write: Joi.string().allow(null, '').optional(),
	ats_application_read: Joi.string().allow(null, '').optional(),
	ats_application_write: Joi.string().allow(null, '').optional(),
	ats_applicationstatus_read: Joi.string().allow(null, '').optional(),
	ats_candidate_read: Joi.string().allow(null, '').optional(),
	ats_candidate_write: Joi.string().allow(null, '').optional(),
	ats_interview_read: Joi.string().allow(null, '').optional(),
	ats_interview_write: Joi.string().allow(null, '').optional(),
	ats_job_read: Joi.string().allow(null, '').optional(),
	ats_job_write: Joi.string().allow(null, '').optional(),
	ats_company_read: Joi.string().allow(null, '').optional(),
	ats_company_write: Joi.string().allow(null, '').optional(),
	ats_document_read: Joi.string().allow(null, '').optional(),
	ats_document_write: Joi.string().allow(null, '').optional(),
	ats_scorecard_read: Joi.string().allow(null, '').optional(),
	ats_scorecard_write: Joi.string().allow(null, '').optional(),
	crm_company_read: Joi.string().allow(null, '').optional(),
	crm_company_write: Joi.string().allow(null, '').optional(),
	crm_contact_read: Joi.string().allow(null, '').optional(),
	crm_contact_write: Joi.string().allow(null, '').optional(),
	crm_deal_read: Joi.string().allow(null, '').optional(),
	crm_deal_write: Joi.string().allow(null, '').optional(),
	crm_event_read: Joi.string().allow(null, '').optional(),
	crm_event_write: Joi.string().allow(null, '').optional(),
	crm_lead_read: Joi.string().allow(null, '').optional(),
	crm_lead_write: Joi.string().allow(null, '').optional(),
	crm_pipeline_read: Joi.string().allow(null, '').optional(),
	crm_pipeline_write: Joi.string().allow(null, '').optional(),
	martech_list_read: Joi.string().allow(null, '').optional(),
	martech_list_write: Joi.string().allow(null, '').optional(),
	martech_member_read: Joi.string().allow(null, '').optional(),
	martech_member_write: Joi.string().allow(null, '').optional(),
	ticketing_customer_read: Joi.string().allow(null, '').optional(),
	ticketing_customer_write: Joi.string().allow(null, '').optional(),
	ticketing_ticket_read: Joi.string().allow(null, '').optional(),
	ticketing_ticket_write: Joi.string().allow(null, '').optional(),
	ticketing_note_read: Joi.string().allow(null, '').optional(),
	ticketing_note_write: Joi.string().allow(null, '').optional(),
	ticketing_category_read: Joi.string().allow(null, '').optional(),
	ticketing_category_write: Joi.string().allow(null, '').optional(),
	hris_employee_read: Joi.string().allow(null, '').optional(),
	hris_employee_write: Joi.string().allow(null, '').optional(),
	hris_group_read: Joi.string().allow(null, '').optional(),
	hris_group_write: Joi.string().allow(null, '').optional(),
	hris_payslip_read: Joi.string().allow(null, '').optional(),
	hris_payslip_write: Joi.string().allow(null, '').optional(),
	hris_timeoff_read: Joi.string().allow(null, '').optional(),
	hris_timeoff_write: Joi.string().allow(null, '').optional(),
	hris_timeshift_read: Joi.string().allow(null, '').optional(),
	hris_timeshift_write: Joi.string().allow(null, '').optional(),
	hris_company_read: Joi.string().allow(null, '').optional(),
	hris_company_write: Joi.string().allow(null, '').optional(),
	hris_location_read: Joi.string().allow(null, '').optional(),
	hris_location_write: Joi.string().allow(null, '').optional(),
	hris_device_read: Joi.string().allow(null, '').optional(),
	hris_device_write: Joi.string().allow(null, '').optional(),
	hris_deduction_read: Joi.string().allow(null, '').optional(),
	hris_deduction_write: Joi.string().allow(null, '').optional(),
	hris_benefit_read: Joi.string().allow(null, '').optional(),
	hris_benefit_write: Joi.string().allow(null, '').optional(),
	uc_call_read: Joi.string().allow(null, '').optional(),
	uc_contact_read: Joi.string().allow(null, '').optional(),
	uc_contact_write: Joi.string().allow(null, '').optional(),
	uc_comment_read: Joi.string().allow(null, '').optional(),
	uc_comment_write: Joi.string().allow(null, '').optional(),
	uc_recording_read: Joi.string().allow(null, '').optional(),
	storage_file_read: Joi.string().allow(null, '').optional(),
	storage_file_write: Joi.string().allow(null, '').optional(),
	webhook: Joi.string().allow(null, '').optional(),
	genai_model_read: Joi.string().allow(null, '').optional(),
	genai_prompt_read: Joi.string().allow(null, '').optional(),
	genai_prompt_write: Joi.string().allow(null, '').optional(),
	genai_embedding_read: Joi.string().allow(null, '').optional(),
	genai_embedding_write: Joi.string().allow(null, '').optional(),
	messaging_message_read: Joi.string().allow(null, '').optional(),
	messaging_message_write: Joi.string().allow(null, '').optional(),
	messaging_channel_read: Joi.string().allow(null, '').optional(),
	messaging_event_read: Joi.string().allow(null, '').optional(),
	messaging_event_write: Joi.string().allow(null, '').optional(),
	kms_space_read: Joi.string().allow(null, '').optional(),
	kms_space_write: Joi.string().allow(null, '').optional(),
	kms_page_read: Joi.string().allow(null, '').optional(),
	kms_page_write: Joi.string().allow(null, '').optional(),
	kms_comment_read: Joi.string().allow(null, '').optional(),
	kms_comment_write: Joi.string().allow(null, '').optional(),
	task_project_read: Joi.string().allow(null, '').optional(),
	task_project_write: Joi.string().allow(null, '').optional(),
	task_task_read: Joi.string().allow(null, '').optional(),
	task_task_write: Joi.string().allow(null, '').optional(),
	task_change_read: Joi.string().allow(null, '').optional(),
	task_comment_read: Joi.string().allow(null, '').optional(),
	task_comment_write: Joi.string().allow(null, '').optional(),
	scim_users_read: Joi.string().allow(null, '').optional(),
	scim_users_write: Joi.string().allow(null, '').optional(),
	scim_groups_read: Joi.string().allow(null, '').optional(),
	scim_groups_write: Joi.string().allow(null, '').optional(),
	lms_course_read: Joi.string().allow(null, '').optional(),
	lms_course_write: Joi.string().allow(null, '').optional(),
	lms_class_read: Joi.string().allow(null, '').optional(),
	lms_class_write: Joi.string().allow(null, '').optional(),
	lms_student_read: Joi.string().allow(null, '').optional(),
	lms_student_write: Joi.string().allow(null, '').optional(),
	lms_instructor_read: Joi.string().allow(null, '').optional(),
	lms_instructor_write: Joi.string().allow(null, '').optional(),
	repo_organization_read: Joi.string().allow(null, '').optional(),
	repo_organization_write: Joi.string().allow(null, '').optional(),
	repo_repository_read: Joi.string().allow(null, '').optional(),
	repo_repository_write: Joi.string().allow(null, '').optional(),
	repo_branch_read: Joi.string().allow(null, '').optional(),
	repo_branch_write: Joi.string().allow(null, '').optional(),
	repo_commit_read: Joi.string().allow(null, '').optional(),
	repo_commit_write: Joi.string().allow(null, '').optional(),
	repo_pullrequest_read: Joi.string().allow(null, '').optional(),
	repo_pullrequest_write: Joi.string().allow(null, '').optional(),
	metadata_metadata_read: Joi.string().allow(null, '').optional(),
	metadata_metadata_write: Joi.string().allow(null, '').optional(),
	calendar_calendar_read: Joi.string().allow(null, '').optional(),
	calendar_calendar_write: Joi.string().allow(null, '').optional(),
	calendar_event_read: Joi.string().allow(null, '').optional(),
	calendar_event_write: Joi.string().allow(null, '').optional(),
	calendar_busy_read: Joi.string().allow(null, '').optional(),
	calendar_link_read: Joi.string().allow(null, '').optional(),
	calendar_link_write: Joi.string().allow(null, '').optional(),
	calendar_recording_read: Joi.string().allow(null, '').optional(),
	calendar_recording_write: Joi.string().allow(null, '').optional(),
	enrich_person_read: Joi.string().allow(null, '').optional(),
	enrich_company_read: Joi.string().allow(null, '').optional(),
	ads_ad_read: Joi.string().allow(null, '').optional(),
	ads_ad_write: Joi.string().allow(null, '').optional(),
	ads_campaign_read: Joi.string().allow(null, '').optional(),
	ads_campaign_write: Joi.string().allow(null, '').optional(),
	ads_group_read: Joi.string().allow(null, '').optional(),
	ads_group_write: Joi.string().allow(null, '').optional(),
	ads_report_read: Joi.string().allow(null, '').optional(),
	ads_organization_read: Joi.string().allow(null, '').optional(),
	ads_organization_write: Joi.string().allow(null, '').optional(),
}).label('map_IntegrationPermission_string');

export const joiApiCall = Joi.object({
	id: Joi.string().allow(null).description('Unique identifier for this API call').meta( { readonly: true }).optional(),
	created_at: Joi.date().allow(null).description('The date that this object was created').meta( { readonly: true }).optional(),
	connection_id: Joi.string().allow(null).optional(),
	workspace_id: Joi.string().meta( { readonly: true }).optional(),
	integration_type: Joi.string().allow('').description('The integration type').required(),
	external_xref: Joi.string().allow(null, '').description('your customer\'s user ID').optional(),
	name: Joi.string().allow('').description('The called name of the API method').required(),
	path: Joi.string().allow('').description('The called API method\'s HTTP verb and route path (PUT /crm/{integration}/deak/{id})').required(),
	size: Joi.number().allow(null).description('The size of the response').optional(),
	status: Joi.string().allow('').description('The resulting HTTP status code (200)').required(),
	error: Joi.string().allow(null, '').description('The error description (if status code is >= 400)').optional(),
	ip_address: Joi.string().allow(null, '').optional(),
	type: joiApiCallType.description('The type of API Call being logged').required(),
	method: Joi.string().allow('').required(),
	environment: Joi.string().allow(null, '').default('Production').optional(),
	webhook_id: Joi.string().allow(null).optional(),
	is_billable: Joi.boolean().allow(null).optional(),
}).label('ApiCall');

export const joiConnectionAuth = Joi.object({
	token: Joi.string().allow(null, '').optional(),
	access_token: Joi.string().allow(null, '').optional(),
	refresh_token: Joi.string().allow(null, '').optional(),
	expiry_date: Joi.date().allow(null).optional(),
	expires_in: Joi.number().allow(null).optional(),
	emails: Joi.array().items(Joi.string().email( { tlds: { allow: false } } ).allow(null, '')).optional(),
	name: Joi.string().allow(null, '').optional(),
	user_id: Joi.string().allow(null, '').optional(),
	app_id: Joi.string().allow(null, '').optional(),
	client_id: Joi.string().allow(null, '').optional(),
	client_secret: Joi.string().allow(null, '').optional(),
	consumer_key: Joi.string().allow(null, '').optional(),
	consumer_secret: Joi.string().allow(null, '').optional(),
	meta: Joi.any().allow(null).meta( { readonly: true }).optional(),
	state: Joi.string().allow(null, '').optional(),
	other_auth_info: Joi.array().items(Joi.string().allow(null, '')).description('When integration.auth_type = "other", this field contains the authentication credentials in the same order as token_names').optional(),
	api_url: Joi.string().uri().allow(null, '').optional(),
	authorize_url: Joi.string().uri().allow(null, '').optional(),
	token_url: Joi.string().uri().allow(null, '').optional(),
	refresh_url: Joi.string().uri().allow(null, '').optional(),
	pem: Joi.string().allow(null, '').description('the PEM X.509 certificate in Base64 ASCII format').optional(),
	key: Joi.string().allow(null, '').description('the private KEY X.509 certificate in Base64 ASCII format').optional(),
	refresh_token_expires_in: Joi.number().allow(null).optional(),
	refresh_token_expires_date: Joi.date().allow(null).optional(),
	dev_api_key: Joi.string().allow(null, '').optional(),
}).label('ConnectionAuth').description('An authentication object that represents a specific authorized user\'s connection to an integration.');

export const joiConnection = Joi.object({
	id: Joi.string().allow(null).description('Unique identifier for this integration object').meta( { readonly: true }).optional(),
	created_at: Joi.date().allow(null).description('The date that this integration object was created').meta( { readonly: true }).optional(),
	updated_at: Joi.date().allow(null).description('The last date that this integration object was updated').meta( { readonly: true }).optional(),
	workspace_id: Joi.string().meta( { readonly: true }).optional(),
	integration_type: Joi.string().allow('').description('The integration type').required(),
	integration_name: Joi.string().allow(null, '').optional(),
	external_xref: Joi.string().allow(null, '').description('customer\'s user ID').optional(),
	permissions: Joi.array().items(joiIntegrationPermission).required(),
	categories: Joi.array().items(joiIntegrationCategory).description('The Integration categories that this connection supports').required(),
	auth: joiConnectionAuth.allow(null).optional(),
	is_paused: Joi.boolean().allow(null).description('Whether this integration has exceed the monthly limit of the plan').meta( { readonly: true }).optional(),
	auth_aws_arn: Joi.string().allow(null, '').description('the AWS ARN / secretID for the stored auth field').optional(),
	environment: Joi.string().allow(null, '').default('Production').optional(),
	last_healthy_at: Joi.date().allow(null).meta( { readonly: true }).optional(),
	last_unhealthy_at: Joi.date().allow(null).meta( { readonly: true }).optional(),
}).label('Connection').description('A connection represents a specific authentication of an integration.');

export const joiIntegrationSupport = Joi.object({
	methods: Joi.object().pattern(Joi.string(), Joi.boolean().optional().allow(null)).allow(null).optional(),
	inbound_fields: Joi.object().pattern(Joi.string(), joiSupportInboundType.optional().allow(null, '')).allow(null).optional(),
	outbound_fields: Joi.object().pattern(Joi.string(), joiSupportOutboundType.optional().allow(null, '')).allow(null).optional(),
	webhook_events: joimap_WebhookEvent_IntegrationSupportWebhookType.optional(),
	raw_objects: Joi.array().items(Joi.string().allow(null, '')).description('objects that we map from in the integration').optional(),
	slow_fields: Joi.array().items(Joi.string().allow(null, '')).optional(),
	from_webhook: joiSupportInboundType.allow(null).optional(),
	list_sort_by_name: joiSupportInboundType.allow(null).optional(),
	list_sort_by_created_at: joiSupportInboundType.allow(null).optional(),
	list_sort_by_updated_at: joiSupportInboundType.allow(null).optional(),
	list_updated_gte: joiSupportInboundType.allow(null).optional(),
	list_user_id: joiSupportInboundType.allow(null).optional(),
	list_user_mentioned_id: joiSupportInboundType.allow(null).optional(),
	list_customer_id: joiSupportInboundType.allow(null).optional(),
	list_company_id: joiSupportInboundType.allow(null).optional(),
	list_contact_id: joiSupportInboundType.allow(null).optional(),
	list_application_id: joiSupportInboundType.allow(null).optional(),
	list_candidate_id: joiSupportInboundType.allow(null).optional(),
	list_deal_id: joiSupportInboundType.allow(null).optional(),
	list_job_id: joiSupportInboundType.allow(null).optional(),
	list_invoice_id: joiSupportInboundType.allow(null).optional(),
	list_order: joiSupportInboundType.allow(null).optional(),
	list_query: joiSupportInboundType.allow(null).optional(),
	list_limit: joiSupportInboundType.allow(null).optional(),
	list_offset: joiSupportInboundType.allow(null).optional(),
	list_root_id: joiSupportInboundType.allow(null).optional(),
	list_list_id: joiSupportInboundType.allow(null).optional(),
	list_interview_id: joiSupportInboundType.allow(null).optional(),
	list_location_id: joiSupportInboundType.allow(null).optional(),
	list_collection_id: joiSupportInboundType.allow(null).optional(),
	list_ticket_id: joiSupportInboundType.allow(null).optional(),
	list_parent_id: joiSupportInboundType.allow(null).optional(),
	list_account_id: joiSupportInboundType.allow(null).optional(),
	list_item_id: joiSupportInboundType.allow(null).optional(),
	list_space_id: joiSupportInboundType.allow(null).optional(),
	list_channel_id: joiSupportInboundType.allow(null).optional(),
	list_page_id: joiSupportInboundType.allow(null).optional(),
	list_type: joiSupportInboundType.allow(null).optional(),
	list_link_id: joiSupportInboundType.allow(null).optional(),
	list_project_id: joiSupportInboundType.allow(null).optional(),
	list_item_variant_id: joiSupportInboundType.allow(null).optional(),
	list_raw_fields: joiSupportInboundType.allow(null).optional(),
	list_student_id: joiSupportInboundType.allow(null).optional(),
	list_class_id: joiSupportInboundType.allow(null).optional(),
	list_instructor_id: joiSupportInboundType.allow(null).optional(),
	list_course_id: joiSupportInboundType.allow(null).optional(),
	list_teacher_id: joiSupportInboundType.allow(null).optional(),
	list_repo_id: joiSupportInboundType.allow(null).optional(),
	list_org_id: joiSupportInboundType.allow(null).optional(),
	list_calendar_id: joiSupportInboundType.allow(null).optional(),
	list_task_id: joiSupportInboundType.allow(null).optional(),
	search_twitter: joiSupportInboundType.allow(null).optional(),
	search_name: joiSupportInboundType.allow(null).optional(),
	search_linkedinurl: joiSupportInboundType.allow(null).optional(),
	search_email: joiSupportInboundType.allow(null).optional(),
	search_domain: joiSupportInboundType.allow(null).optional(),
	list_event_id: joiSupportInboundType.allow(null).optional(),
	list_start_gte: joiSupportInboundType.allow(null).optional(),
	list_end_lt: joiSupportInboundType.allow(null).optional(),
	list_end_le: joiSupportInboundType.allow(null).description('@deprecated; use list_end_lt').optional(),
	list_lead_id: joiSupportInboundType.allow(null).optional(),
	list_call_id: joiSupportInboundType.allow(null).optional(),
	list_document_id: joiSupportInboundType.allow(null).optional(),
	list_payment_id: joiSupportInboundType.allow(null).optional(),
	list_status: joiSupportInboundType.allow(null).optional(),
	list_branch_id: joiSupportInboundType.allow(null).optional(),
	list_pipeline_id: joiSupportInboundType.allow(null).optional(),
	list_category_id: joiSupportInboundType.allow(null).optional(),
	list_package_id: joiSupportInboundType.allow(null).optional(),
	list_expand: joiSupportInboundType.allow(null).optional(),
	list_expand_recurring_events: joiSupportInboundType.allow(null).description('@deprecated; use list_expand').optional(),
	native_webhook_parent_id: joiSupportInboundType.allow(null).optional(),
	native_webhook_project_id: joiSupportInboundType.allow(null).optional(),
	native_webhook_company_id: joiSupportInboundType.allow(null).optional(),
	native_webhook_task_id: joiSupportInboundType.allow(null).optional(),
	native_webhook_channel_id: joiSupportInboundType.allow(null).optional(),
	native_webhook_calendar_id: joiSupportInboundType.allow(null).optional(),
	native_webhook_event_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_updated_gte: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_limit: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_channel_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_parent_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_contact_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_deal_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_company_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_user_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_user_mentioned_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_type: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_ticket_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_expand: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_status: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_start_gte: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_end_lt: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_end_le: joiSupportInboundType.allow(null).description('@deprecated; use virtual_webhook_end_lt').optional(),
	virtual_webhook_task_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_space_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_repo_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_project_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_pipeline_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_page_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_org_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_location_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_list_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_job_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_item_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_fields: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_event_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_customer_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_collection_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_candidate_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_call_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_branch_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_application_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_item_variant_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_calendar_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_lead_id: joiSupportInboundType.allow(null).optional(),
	list_payslip_id: joiSupportInboundType.allow(null).optional(),
	list_benefit_id: joiSupportInboundType.allow(null).optional(),
	list_saleschannel_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_saleschannel_id: joiSupportInboundType.allow(null).optional(),
	list_campaign_id: joiSupportInboundType.allow(null).optional(),
	list_ad_id: joiSupportInboundType.allow(null).optional(),
	list_group_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_campaign_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_ad_id: joiSupportInboundType.allow(null).optional(),
	virtual_webhook_group_id: joiSupportInboundType.allow(null).optional(),
}).label('IntegrationSupport');

export const joiIntegration = Joi.object({
	type: Joi.string().allow('').description('Identifier for this integration').required(),
	created_at: Joi.string().allow(null, '').description('Date that this integration was supported (YYYY-MM-DD)').optional(),
	updated_at: Joi.string().allow(null, '').description('YYYY-MM-DD').optional(),
	name: Joi.string().allow('').description('The integration\'s name').required(),
	is_active: Joi.boolean().allow(null).description('Is this integration active in this workspace').optional(),
	categories: Joi.array().items(joiIntegrationCategory).description('The categories of support solutions that this integration has').required(),
	api_docs_url: Joi.string().uri().allow(null, '').description('The URL of the integration\'s API documentation').optional(),
	logo_url: Joi.string().uri().allow(null, '').description('The URL of the integration\'s logo').optional(),
	in_progress: Joi.boolean().allow(null).description('If this integration is not yet available as it is currently being built by unified.to').optional(),
	color: Joi.string().allow(null, '').description('button background color for AUTH').optional(),
	text_color: Joi.string().allow(null, '').description('text color for AUTH').optional(),
	fa_icon: Joi.string().allow(null, '').description('font-awesome icon').optional(),
	token_names: Joi.array().items(Joi.string().allow(null, '')).description('if auth_types = \'token\'').optional(),
	token_instructions: Joi.array().items(Joi.string().allow(null, '')).description('instructions for the user on how to find the token/key').optional(),
	web_url: Joi.string().uri().allow(null, '').description('URL for the software vendor').optional(),
	rate_limit_description: Joi.string().allow(null, '').optional(),
	beta: Joi.boolean().allow(null).description('This integration is new and is still considered "beta"').optional(),
	support: Joi.object().pattern(Joi.string(), joiIntegrationSupport.optional().allow(null)).allow(null).optional(),
	tested_at: Joi.date().allow(null).optional(),
	sandbox: Joi.any().allow(null).optional(),
	partnership: Joi.any().allow(null).optional(),
	saml: Joi.any().allow(null).optional(),
	description: Joi.string().allow(null, '').optional(),
	api: Joi.any().allow(null).optional(),
	featured: Joi.boolean().allow(null).optional(),
	popularity: Joi.number().allow(null).optional(),
	active_healthy_connections: Joi.number().allow(null).optional(),
}).label('Integration').description('Informational object for supported integrations.');

export const joiInvoice = Joi.object({
	stripe_id: Joi.string().allow('').required(),
	created_at: Joi.date().required(),
	amount: Joi.number().required(),
	connections: Joi.number().required(),
	plan: Joi.string().allow('').required(),
}).label('Invoice');

export const joiIssue = Joi.object({
	id: Joi.string().allow(null).optional(),
	created_at: Joi.string().allow(null, '').optional(),
	updated_at: Joi.string().allow(null, '').optional(),
	title: Joi.string().allow('').required(),
	status: joiIssueStatus.required(),
	url: Joi.string().uri().allow(null, '').optional(),
	workspace_id: Joi.string().required(),
	type: Joi.array().items(Joi.string().allow(null, '')).optional(),
	resolution_time: Joi.number().allow(null).optional(),
	ticket_ref: Joi.string().allow('').required(),
	size: Joi.number().allow(null).description('1-5, 1 is lowest').optional(),
	importance: Joi.number().allow(null).description('1-5, 1 is lowest').optional(),
}).label('Issue');

export const joiNotification = Joi.object({
	id: Joi.string().allow(null).description('Unique identifier for this notification object').meta( { readonly: true }).optional(),
	created_at: Joi.date().allow(null).description('The date that this integration object was created').meta( { readonly: true }).optional(),
	workspace_id: Joi.string().allow(null).meta( { readonly: true }).optional(),
	description: Joi.string().allow(null, '').description('Longer description of this notification').optional(),
	user_id: Joi.string().allow(null).optional(),
	user_name: Joi.string().allow(null, '').optional(),
	workspace_name: Joi.string().allow(null, '').optional(),
	webhook_id: Joi.string().allow(null).optional(),
	connection_id: Joi.string().allow(null).optional(),
	integration_type: Joi.string().allow(null, '').optional(),
	integration_name: Joi.string().allow(null, '').optional(),
	sent_at: Joi.date().allow(null).optional(),
	event: joiWorkspaceEventType.allow(null).optional(),
}).label('Notification').description('A notification of an event that occurred in you account.');

export const joiPermission = Joi.object({
	can_create_org: Joi.boolean().meta( { readonly: true }).optional(),
	can_leave_org: Joi.boolean().meta( { readonly: true }).optional(),
	can_downgrade: Joi.boolean().meta( { readonly: true }).optional(),
	can_invite: Joi.boolean().meta( { readonly: true }).optional(),
	can_update_org: Joi.boolean().meta( { readonly: true }).optional(),
	can_add_and_remove_admin: Joi.boolean().meta( { readonly: true }).optional(),
	can_accept_invite: Joi.boolean().meta( { readonly: true }).optional(),
	can_reject_invite: Joi.boolean().meta( { readonly: true }).optional(),
	can_pay: Joi.boolean().meta( { readonly: true }).optional(),
	can_get_invoices: Joi.boolean().meta( { readonly: true }).optional(),
	is_admin: Joi.boolean().meta( { readonly: true }).optional(),
}).label('Permission');

export const joiPlan = Joi.object({
	test_stripe_product_id: Joi.string().allow(null, '').optional(),
	test_stripe_price_id: Joi.string().allow(null, '').optional(),
	min_annual_price: Joi.number().allow(null).optional(),
	stripe_annual_price_id: Joi.string().allow(null, '').optional(),
	test_stripe_annual_price_id: Joi.string().allow(null, '').optional(),
	stripe_overage_price_id: Joi.string().allow(null, '').optional(),
	test_stripe_overage_price_id: Joi.string().allow(null, '').optional(),
	dedicated_channel: Joi.boolean().allow(null).description('Dedicated Slack/Discord channel').optional(),
}).label('Plan');

export const joiUser = Joi.object({
	id: Joi.string().allow(null).meta( { readonly: true }).optional(),
	created_at: Joi.date().allow(null).meta( { readonly: true }).optional(),
	updated_at: Joi.date().allow(null).meta( { readonly: true }).optional(),
	name: Joi.string().allow('').required(),
	email: Joi.string().email( { tlds: { allow: false } } ).allow('').meta( { readonly: true }).optional(),
	workspace_id: Joi.string().description('The current workspace').required(),
	workspace_ids: Joi.array().items(Joi.string()).description('A list of all of the user\'s workspaces').required(),
	environment: Joi.string().allow(null, '').default('Production').optional(),
	meta: Joi.any().allow(null).optional(),
}).label('User').description('The User object represents you on the system. A user can belong to multiple workspaces (ie. organizations).');

export const joiWebhook = Joi.object({
	id: Joi.string().allow(null).meta( { readonly: true }).optional(),
	created_at: Joi.date().allow(null).meta( { readonly: true }).optional(),
	updated_at: Joi.date().allow(null).meta( { readonly: true }).optional(),
	workspace_id: Joi.string().allow(null).meta( { readonly: true }).optional(),
	connection_id: Joi.string().required(),
	hook_url: Joi.string().allow(null, '').description('The URL of the webhook').optional(),
	object_type: joiObjectType.description('The object to return (eg. CRM "contact")').required(),
	interval: Joi.number().allow(null).description('The interval (in minutes) to check for updated/new objets. ').optional(),
	checked_at: Joi.date().description('The last date/time that a check was done on this object').meta( { readonly: true }).optional(),
	integration_type: Joi.string().allow('').meta( { readonly: true }).optional(),
	environment: Joi.string().allow(null, '').default('Production').meta( { readonly: true }).optional(),
	event: joiWebhookEvent.required(),
	runs: Joi.array().items(Joi.string().allow(null, '')).description('An array of the most revent virtual webhook runs').meta( { readonly: true }).optional(),
	fields: Joi.string().allow(null, '').optional(),
	webhook_type: joiIntegrationSupportWebhookType.allow(null).optional(),
	meta: Joi.any().allow(null).meta( { readonly: true }).optional(),
	is_healthy: Joi.boolean().allow(null).meta( { readonly: true }).optional(),
	page_max_limit: Joi.number().allow(null).optional(),
	filters: Joi.object().pattern(Joi.string(), Joi.string().optional().allow(null,'')).allow(null).optional(),
	db_type: joiWebhookDatabaseType.allow(null).optional(),
	db_url: Joi.string().uri().allow(null, '').optional(),
	db_schema: Joi.string().allow(null, '').optional(),
	db_name_prefix: Joi.string().allow(null, '').optional(),
	is_paused: Joi.boolean().allow(null).optional(),
}).label('Webhook').description('A webhook is used to POST new/updated information to your server.');

export const joiWebhookData = Joi.object({
	data: Joi.array().items(Joi.any()).description('The data array will contact an array of specific objects according to the webhook\'s connection. (eg. CRM Contacts)').required(),
	webhook: joiWebhook.description('The webhook object').required(),
	nonce: Joi.string().allow('').description('random string').required(),
	sig: Joi.string().allow(null, '').description('@deprecated; use sig256 instead').optional(),
	sig256: Joi.string().allow(null, '').description('HMAC-SHA256(workspace.secret, data + nonce)').optional(),
	type: joiWebhookDataType.required(),
	external_xref: Joi.string().allow(null, '').optional(),
}).label('WebhookData');

export const joiWorkspaceIntegration = Joi.object({
	integration_type: Joi.string().allow('').required(),
	client_id: Joi.string().allow(null, '').optional(),
	client_secret: Joi.string().allow(null, '').optional(),
	consumer_key: Joi.string().allow(null, '').optional(),
	consumer_secret: Joi.string().allow(null, '').optional(),
	is_active: Joi.boolean().required(),
	api_url: Joi.string().allow(null, '').optional(),
	authorize_url: Joi.string().allow(null, '').optional(),
	token_url: Joi.string().allow(null, '').optional(),
	refresh_url: Joi.string().uri().allow(null, '').optional(),
	base_url: Joi.string().allow(null, '').optional(),
	pem: Joi.string().allow(null, '').description('the PEM X.509 certificate in Base64 ASCII format').optional(),
	key: Joi.string().allow(null, '').description('the private KEY X.509 certificate in Base64 ASCII format').optional(),
	environment: Joi.string().allow(null, '').default('Production').description('authentication environment').optional(),
	categories: Joi.array().items(joiIntegrationCategory).optional(),
	dev_api_key: Joi.string().allow(null, '').optional(),
	overriden_scopes: joimap_IntegrationPermission_string.allow(null).optional(),
}).label('WorkspaceIntegration');

export const joiWorkspace = Joi.object({
	id: Joi.string().allow(null).meta( { readonly: true }).optional(),
	created_at: Joi.date().allow(null).meta( { readonly: true }).optional(),
	updated_at: Joi.date().allow(null).meta( { readonly: true }).optional(),
	name: Joi.string().allow('').required(),
	admin_ids: Joi.array().items(Joi.string()).description('Only these users can add additional admins and invite other users').meta( { readonly: true }).optional(),
	invited_emails: Joi.array().items(Joi.string().allow(null, '')).meta( { readonly: true }).optional(),
	pay_user_id: Joi.string().allow(null, '').meta( { readonly: true }).optional(),
	plan: Joi.string().allow(null, '').meta( { readonly: true }).optional(),
	stripe_customer: Joi.string().allow(null, '').meta( { readonly: true }).optional(),
	stripe_subscriptions: Joi.array().items(Joi.string().allow(null, '')).meta( { readonly: true }).optional(),
	stripe_prices: Joi.array().items(Joi.string().allow(null, '')).meta( { readonly: true }).optional(),
	secret: Joi.string().allow(null, '').description('Workspace API secret').meta( { readonly: true }).optional(),
	integrations: Joi.array().items(joiWorkspaceIntegration).description('Workspace active integrations').meta( { readonly: true }).optional(),
	ip_addresses: Joi.array().items(Joi.string().allow(null, '')).description('a list of IP addresses that are allowed to access this workspace').optional(),
	aws_region: Joi.string().allow(null, '').optional(),
	aws_key: Joi.string().allow(null, '').optional(),
	aws_secret: Joi.string().allow(null, '').optional(),
	datadog_apikey: Joi.string().allow(null, '').optional(),
	datadog_site: Joi.string().allow(null, '').optional(),
	environments: Joi.array().items(Joi.string().allow(null, '')).description('a list of authentication environments for the workspace integrations').optional(),
	add_ons: Joi.array().items(Joi.string().allow(null, '')).optional(),
	checklist: Joi.any().allow(null).optional(),
	plan_term: joiPlanTerm.allow(null).default('monthly').description('monthly or yearly').optional(),
	stripe_canceling_at: Joi.date().allow(null).optional(),
	domain: Joi.string().allow(null, '').description('when set, users of the same domain will auto-join this workspace.  must not be gmail.com or other public domains').optional(),
	event_webhook_url: Joi.string().uri().allow(null, '').optional(),
	event_webhook_events: Joi.array().items(joiWorkspaceEventType).optional(),
	custom_auth_domain: Joi.string().allow(null, '').optional(),
	custom_auth_domain_valid: Joi.boolean().allow(null).optional(),
	custom_api_domain: Joi.string().allow(null, '').optional(),
	slow_fields_opt_in: Joi.boolean().allow(null).optional(),
	notion_verification_token: Joi.string().allow(null, '').optional(),
	favicon_url: Joi.string().uri().allow(null, '').optional(),
	is_baa: Joi.boolean().allow(null).optional(),
	saml_integration_type: Joi.string().allow(null, '').optional(),
	saml_idp_url: Joi.string().allow(null, '').optional(),
	saml_idp_entity_id: Joi.string().allow(null, '').optional(),
	saml_pem: Joi.string().allow(null, '').description('the PEM X.509 certificate in Base64 ASCII format').optional(),
	saml_only_login: Joi.boolean().allow(null).description('if true, only allow SAML login').optional(),
}).label('Workspace').description('The User\'s workspace object. A workspace is like an organization that one or more users belong to.');

